name: Publish

on:
  #   push:
  #     branches: ["main"]
  #     tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The tag to publish
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish Crate
        id: publish-crate
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_PUBLISH }}

      - name: if RPM published
        if: fromJSON(steps.publish-crate.outputs.published).*
        run: |
          LIST="${{ join(fromJSON(steps.publish-crate.outputs.published).*.name, ', ') }}"
          echo "Published crate: $LIST"
