name: Publish

on:
  #   push:
  #     branches: ["main"]
  #     tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The tag to publish
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Publish
        uses: katyo/publish-crates@v2
        id: publish-crates
        with:
          registry_token: ${{ secrets.CRATES_IO_PUBLISH }}
          ignore-unpublished-changes: true
          dry_run: ${{ github.event_name != 'push' }}
      - name: if RPM published
        if: fromJSON(steps.publish-crates.outputs.published).*
        run: |
          LIST="${{ join(fromJSON(steps.publish-crates.outputs.published).*.name, ', ') }}"
          echo "Published crates: $LIST"
