name: Publish

on:
  #   push:
  #     branches: ["main"]
  #     tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The tag to publish
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Publish
        uses: katyo/publish-crates@v2
        with:
          registry_token: ${{ secrets.CRATES_IO_PUBLISH }}
          dry_run: ${{ github.event_name != 'push' }}
