name: Publish to Cargo

on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish"

    steps:
      - uses: actions/checkout@v4

      - name: Cache publish-action bin
        id: cache-publish-action
        uses: actions/cache@v4
        env:
          cache-name: cache-publish-action
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.4.0

      - name: Install publish-action
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        run: cargo install publish-action --version=0.4.0

      - name: Run publish-action
        id: publish-action
        run: publish-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_PUBLISH }}
